### ISSUE TITLE
Decide on command name

### ISSUE THREAD

**Issue by schlessera** [wp-cli/makepot-command#11]
@miya0001 : 
> `makepot` is verb, but other commands on wp-cli are noun. Is it ok?

We should discuss the best name for this command, as `wp makepot` is less than ideal.

Options so far:
`wp i18n ...`
`wp translations ...`
`wp pot make`

@swissspidy :
> I'd prefer `wp i18n`, e.g. `wp i18n makepot` or `wp i18n addtextdomain`

**Comment by kjohnson** [comment]
Would `gettext` be the WordPress noun for this?
Seems to match the language of the related filter: https://codex.wordpress.org/Plugin_API/Filter_Reference/gettext

**Comment by swissspidy** [comment]
Grouping these commands under `wp i18n` would make it possible to add other commands in the future if needed. One such command (`addtextdomain` or `checktextdomain`) is being discussed in #7. Then it could look like this:

* `wp i18n makepot`
* `wp i18n addtextdomain`

Plus, users could use this namespace, if you so will, for their own sub commands.

----

`wp translations` would be too close to `wp language`, which is a command for dealing with translation files in a WP install.

**Comment by schlessera** [comment]
Yes, looks good. We should just use a dash to separate the verb parts:

* `wp i18n make-pot`
* `wp i18n add-text-domain`

**Comment by swissspidy** [comment]
Maybe with another verb then? Perhaps `wp i18n generate-pot` or `wp i18n create-pot`? Or even `wp i18n pot create` (like `wp comment create`).

**Comment by schlessera** [comment]
`wp i18n pot create` sounds like it would be a good fit, but I fear that it might be to close to CRUD and people start to assume they can also `list` and `get` and `delete` and ...

**Comment by swissspidy** [comment]
Another reason for `wp i18n` would be that in the future, WordPress core will likely adopt a (better) way to translate JavaScript applications (like Gutenberg). This means there's a need to extract strings from JavaScript and generate a catalog file for them as well. Jed

If it's possible to do extract these strings with PHP (maybe even with the same library), there could be a new `wp i18n <…>` command in addition to the makepot one.

**Comment by schlessera** [comment]
Okay, to move forward, let's go with the following:

* Use `wp i18n` as the command namespace here.
* Use `wp i18n make-pot` as the subcommand for now. It is the most obvious one, I think.
* Once we further flesh out additional commands, we can reconsider the `make-pot` name and use an alias for back-compat as needed.

**Comment by swissspidy** [comment]
Cool. I'll work on that once #13 is merged, to avoid conflicts.
